[package]
name = "mtpfs"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
mtp = { workspace = true, features = ["usb", "examples"] }

tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync"] }
fuser.workspace = true
futures.workspace = true

# User interaction
env_logger.workspace = true
log.workspace = true
indicatif.workspace = true
dialoguer.workspace = true
