[package]
name = "mtpfs"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
mtp = { path = "../mtp", features = ["usb"] }

tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync"] }
fuser.workspace = true
id_tree.workspace = true
libc.workspace = true
futures.workspace = true

# User interaction
env_logger.workspace = true
log.workspace = true
indicatif.workspace = true
dialoguer.workspace = true
