[package]
name = "mtp"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

#[lints]
#workspace = true

[dependencies]
mtp_spec.workspace = true

tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread", "time"] }
deku = { workspace = true, features = ["alloc", "logging"] }
log.workspace = true
futures.workspace = true

# USB
bitflags = { version = "2", optional = true }
nusb = { version = "0.1", optional = true }

# FS
tempfile = { version = "3", optional = true }

# Time
libc = { version = "0.2", optional = true }

[dev-dependencies]
test-log = "0.2.16"

[features]
default = ["usb", "fs", "time"]

# Transport backends
usb = ["dep:nusb", "dep:bitflags"]

# High-level features
fs = ["dep:tempfile"]
time = ["dep:libc"]
