[package]
name = "mtp"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mtp_spec = { path = "../mtp_spec" }

bitflags = "2"
nusb = "0.1"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread", "time"] }
deku = { path = "../../../Dependencies/deku", default-features = false, features = ["alloc", "logging"] }
log = "0.4.22"

[dev-dependencies]
test-log = "0.2.16"
