[package]
name = "mtp"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
mtp_spec.workspace = true

tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "sync"] }
tokio-stream = { workspace = true, features = ["sync"] }
deku = { workspace = true, features = ["std", "alloc", "logging"] }
log.workspace = true
futures.workspace = true

# USB
bitflags = { workspace = true, optional = true }
nusb = { workspace = true, features = ["tokio"], optional = true }

# FS
tempfile = { workspace = true, optional = true }

# Examples
dialoguer = { workspace = true, optional = true }

[dev-dependencies]
test-log.workspace = true
clap = { workspace = true, features = ["derive"] }

[features]
default = ["usb", "fs", "time"]

# Transport backends
usb = ["dep:bitflags", "dep:nusb"]

# High-level features
fs = ["dep:tempfile"]
time = ["mtp_spec/time"]

examples = ["dep:dialoguer"]

[[example]]
name = "send"
path = "../examples/send.rs"
required-features = ["examples"]
