[package]
name = "mtp_spec"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
bitflags.workspace = true
paste.workspace = true
deku = { workspace = true, default-features = false, features = ["alloc", "logging", "descriptive-errors"] }
log.workspace = true
futures-core.workspace = true
libc = { workspace = true, optional = true }

[dev-dependencies]
mtp.workspace = true
test-log.workspace = true

[features]
time = ["dep:libc"]
