[package]
name = "mtp_spec"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
paste = "1.0.15"
deku = { path = "../../../Dependencies/deku", default-features = false, features = ["alloc", "logging"] }
log = "0.4.22"
seq-macro = "0.3.5"

[dev-dependencies]
test-log = "0.2.16"
deku = { path = "../../../Dependencies/deku", default-features = false, features = ["alloc", "logging"] }
