[package]
name = "mtp_spec"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

#[lints]
#workspace = true

[dependencies]
paste = "1.0.15"
deku = { workspace = true, default-features = false, features = ["alloc", "logging"] }
log.workspace = true
futures-core.workspace = true

# FS
tempfile = { version = "3", optional = true }

# Time
libc = { version = "0.2", optional = true }

[dev-dependencies]
test-log = "0.2.16"

[features]
default = ["fs", "time"]

fs = ["dep:tempfile"]
time = ["dep:libc"]
